//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatSach
    {
        public int Iddatsach { get; set; }
        public Nullable<int> Idsach { get; set; }
        public Nullable<int> Idtaikhoan { get; set; }
        public Nullable<System.DateTime> Ngaymundat { get; set; }
        public string Chat { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
