//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DatSach
    {
        [Key]
        public int Iddatsach { get; set; }

        [Required(ErrorMessage = "Mã sách không được để trống.")]
        public Nullable<int> Idsach { get; set; }

        [Required(ErrorMessage = "Mã tài khoản không được để trống.")]
        public Nullable<int> Idtaikhoan { get; set; }

        [Required(ErrorMessage = "Ngày mượn đặt sách không được để trống.")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Ngaymundat { get; set; }

        [Required(ErrorMessage = "Trường chat không được để trống.")]
        [StringLength(255, ErrorMessage = "Trường chat không được vượt quá 255 ký tự.")]
        public string Chat { get; set; }

        public virtual Sach Sach { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
