//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kiemsoat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kiemsoat()
        {
            this.TrangThaiSachMuons = new HashSet<TrangThaiSachMuon>();
        }

        [Key]
        public int Idkiemsoat { get; set; }

        [Required(ErrorMessage = "Ảnh trạng thái không được để trống.")]
        [StringLength(100, ErrorMessage = "Tên file ảnh không được vượt quá 100 ký tự.")]
        public string Imgtrangthai { get; set; }

        [Required(ErrorMessage = "Trạng thái sách không được để trống.")]
        [StringLength(50, ErrorMessage = "Trạng thái sách không được vượt quá 50 ký tự.")]
        public string Trangthaisach { get; set; }

        [Required(ErrorMessage = "Mã sách không được để trống.")]
        public Nullable<int> Idsach { get; set; }

        public virtual Sach Sach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrangThaiSachMuon> TrangThaiSachMuons { get; set; }
    }
}
