//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuMua()
        {
            this.PhieuMuaChiTiets = new HashSet<PhieuMuaChiTiet>();
        }
    
        public int Idphieu { get; set; }
        public Nullable<int> Idsach { get; set; }
        public Nullable<int> Idtaikhoan { get; set; }
        public Nullable<System.DateTime> Ngaymua { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuaChiTiet> PhieuMuaChiTiets { get; set; }
    }
}
