//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuonChiTiet
    {
        public int IdPhieuMuonChiTiet { get; set; }
        public Nullable<int> IdPhieuMuon { get; set; }
        public Nullable<int> IdSach { get; set; }
        public Nullable<double> Tongtien { get; set; }
        public string TrangThaiSach { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
