//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhieuMua
    {
        public class ckNgayMua : ValidationAttribute
        {
            protected override ValidationResult IsValid(object value, ValidationContext validationContext)
            {
                var ngayMua = (DateTime)value;
                var ngayHienTai = DateTime.Now;

                if (ngayMua.Date > ngayHienTai.Date)
                {
                    return new ValidationResult(ErrorMessage);
                }

                return ValidationResult.Success;
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuMua()
        {
            this.PhieuMuaChiTiets = new HashSet<PhieuMuaChiTiet>();
        }

        [Key]
        public int Idphieu { get; set; }

        [Required(ErrorMessage = "Mã sách không được để trống.")]
        public Nullable<int> Idsach { get; set; }

        [Required(ErrorMessage = "Mã tài khoản không được để trống.")]
        public Nullable<int> Idtaikhoan { get; set; }

        [Required(ErrorMessage = "Ngày mua không được để trống.")]
        [DataType(DataType.Date)]
        [ckNgayMua(ErrorMessage = "Ngày mua không được lớn hơn ngày hiện tại.")]
        public Nullable<System.DateTime> Ngaymua { get; set; }

        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuaChiTiet> PhieuMuaChiTiets { get; set; }
    }
}
