//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhieuMuonChiTiet
    {
        [Key]
        public int IdPhieuMuonChiTiet { get; set; }

        [Display(Name = "Mã phiếu mượn")]
        [Required(ErrorMessage = "Mã phiếu mượn không được để trống")]
        public Nullable<int> IdPhieuMuon { get; set; }

        [Display(Name = "Mã sách")]
        [Required(ErrorMessage = "Mã sách không được để trống")]
        public Nullable<int> IdSach { get; set; }

        [Display(Name = "Tổng tiền")]
        [Required(ErrorMessage = "Tổng tiền không được để trống")]
        [Range(0, double.MaxValue, ErrorMessage = "Tổng tiền không được âm")]
        public Nullable<double> Tongtien { get; set; }

        [Display(Name = "Trạng thái sách")]
        [StringLength(50)]
        [Required(ErrorMessage = "Trạng thái sách không được để trống")]
        public string TrangThaiSach { get; set; }

        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
