//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhieuMuaChiTiet
    {
        [Key]
        public int IdPhieuMuaChiTiet { get; set; }

        [Required(ErrorMessage = "Mã phiếu mua không được để trống.")]
        public Nullable<int> IdPhieuMua { get; set; }

        [Required(ErrorMessage = "Mã sách không được để trống.")]
        public Nullable<int> IdSach { get; set; }

        [Required(ErrorMessage = "Tổng tiền không được để trống.")]
        [Range(0, double.MaxValue, ErrorMessage = "Tổng tiền phải là số không âm.")]
        public Nullable<double> Tongtien { get; set; }

        [Required(ErrorMessage = "Số lượng không được để trống.")]
        [Range(1, int.MaxValue, ErrorMessage = "Số lượng phải là số nguyên dương.")]
        public Nullable<int> SoLuong { get; set; }
        public virtual PhieuMua PhieuMua { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
