//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMua
    {
        public int Idphieu { get; set; }
        public Nullable<int> Idsach { get; set; }
        public Nullable<int> IdTaiKhoan { get; set; }
        public Nullable<double> Tongtien { get; set; }
        public Nullable<System.DateTime> Ngaymua { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
