//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.Kiemsoats = new HashSet<Kiemsoat>();
            this.TrangThaiSachMuons = new HashSet<TrangThaiSachMuon>();
        }
    
        public int Idsach { get; set; }
        public string Tieude { get; set; }
        [Display(Name = "T?i ?nh lên")]
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
        public byte[] ImgSach { get; set; }
        public string Tacgia { get; set; }
        public Nullable<decimal> GiaMua { get; set; }
        public Nullable<int> Namxuatban { get; set; }
        public string Mota { get; set; }
        public Nullable<int> Idloai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kiemsoat> Kiemsoats { get; set; }
        public virtual Loai Loai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrangThaiSachMuon> TrangThaiSachMuons { get; set; }
    }
}
