//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.PhieuMuas = new HashSet<PhieuMua>();
            this.Thes = new HashSet<The>();
        }

        [Key]
        [Display(Name = "Mã người dùng")]
        public int Idtaikhoan { get; set; }

        [Display(Name = "Họ & tên lót")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Họ tên phải từ 1-50 ký tự")]
        [Required]
        public string Holot { get; set; }

        [Display(Name = "Tên")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = "Họ tên phải từ 1-20 ký tự")]
        [Required(ErrorMessage = "Tên không được để trống")]
        public string Ten { get; set; }

        [Display(Name = "Email")]
        [StringLength(50)]
        [Required]
        [EmailAddress(ErrorMessage = "Bạn phải điền email hợp lệ")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Số điện thoại không được để trống")]
        [Phone(ErrorMessage = "Số điện thoại không hợp lệ")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "Số điện thoại phải có 10 chữ số")]
        public string Dienthoai { get; set; }

        [Display(Name = "Mật khẩu")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Mật khẩu phải từ 3-50 ký tự")]
        [Required]
        public string Matkhau { get; set; }
        [Key]
        [Display(Name = "Hình ảnh người dùng")]

        public string ImgU { get; set; }

        [Display(Name = "ID quyền")]
        public Nullable<int> IDQuyen { get; set; }

        [Display(Name = "Địa chỉ")]
        [StringLength(200, MinimumLength = 5, ErrorMessage = "Địa chỉ phải từ 5-200 ký tự")]
        [Required]
        public string Diachi { get; set; }
    
        public virtual PhanQuyen PhanQuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMua> PhieuMuas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<The> Thes { get; set; }
    }
}
