//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class The
    {
        [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
        public sealed class FutureDateAttribute : ValidationAttribute
        {
            protected override ValidationResult IsValid(object value, ValidationContext validationContext)
            {
                if (value != null)
                {
                    DateTime date = (DateTime)value;

                    if (date <= DateTime.Now)
                    {
                        return new ValidationResult("Ngày mở thẻ phải là ngày tương lai");
                    }
                }

                return ValidationResult.Success;
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public The()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }

        [Key]
        public int Idthe { get; set; }

        [Display(Name = "Mã tài khoản")]
        public Nullable<int> Idtaikhoan { get; set; }

        [Display(Name = "Ngày mở thẻ")]
        [Required(ErrorMessage = "Ngày mở thẻ không được để trống")]
        [FutureDate(ErrorMessage = "Ngày mở thẻ phải là ngày tương lai")]
        public Nullable<System.DateTime> Ngaymothe { get; set; }

        [Display(Name = "Trạng thái thẻ")]
        [Required(ErrorMessage = "Trạng thái thẻ không được để trống")]
        public Nullable<int> Trangthaithe { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}

