//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangThaiSachMuon
    {
        public int Idtrangthaisachmuon { get; set; }
        public Nullable<int> Idsach { get; set; }
        public Nullable<int> Idkiemsoat { get; set; }
        public Nullable<int> Idphieu { get; set; }
        public string Trangthaism { get; set; }
    
        public virtual Kiemsoat Kiemsoat { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
