//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TrangThaiSachMuon
    {
        [Key]
        public int Idtrangthaisachmuon { get; set; }

        [Display(Name = "Mã sách")]
        [Required(ErrorMessage = "Mã sách không được để trống")]
        public Nullable<int> Idsach { get; set; }

        [Display(Name = "Mã kiểm soát")]
        [Required(ErrorMessage = "Mã kiểm soát không được để trống")]
        public Nullable<int> Idkiemsoat { get; set; }

        [Display(Name = "Mã phiếu")]
        [Required(ErrorMessage = "Mã phiếu không được để trống")]
        public Nullable<int> Idphieu { get; set; }

        [Display(Name = "Trạng thái sách mượn")]
        [StringLength(50)]
        [Required(ErrorMessage = "Trạng thái sách mượn không được để trống")]
        public string Trangthaism { get; set; }

        public virtual Kiemsoat Kiemsoat { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
